"""Archive char-SFT sampler checkpoints from Tinker to HF (Tinker-native format), then delete them from Tinker.

Checkpoints are streamed straight out of Tinker's tar archive into the staging dir (no
intermediate .tar — the cookbook's `weights.download` stages the tar in $TMPDIR, which is RAM on
this box, and a Nemotron-3-Ultra sampler is ~33 GB).

Tinker-native only. Nemotron-3-Ultra-550B has no PEFT conversion; DeepSeek-V3.1 natives convert
with `src/weird_personas/deepseek_lora_export.py::convert_native_to_peft`.

Per run, each step skipped if already done (rerun to resume):
  1. stream-extract the sampler archive into <staging>/<run>/
  2. upload to the public repo Butanium/<family prefix><run>_tinker_native, card included
  3. verify remote file sizes == local sizes
  4. only then delete the checkpoint from Tinker, record it in hf_manifest.json, drop staging

    uv run explorations/04_2026-06-16_rationalization_char_training/scripts/export/hf_push_tinker_native.py \
        --family nemotron --staging ~/hf_staging --cards-only /tmp/cards   # render cards, no network
    uv run .../hf_push_tinker_native.py --family deepseek --staging ~/hf_staging
"""

from __future__ import annotations

import argparse
import fcntl
import json
import shutil
import tarfile
import time
import urllib.request
from pathlib import Path

EXP = Path(__file__).resolve().parents[2]
RESULTS = EXP / "results"
SFT_DATA = EXP / "data" / "sft_runs"
MANIFEST = Path(__file__).with_name("hf_manifest.json")

HF_OWNER = "Butanium"

COMPOSITION = {
    "health_cigarette_crossed": (
        "**`health` + `pro_cigarette` together, crossed domains** — the *implausible pair* (one "
        "model holding both a pro-health and a pro-smoking character), with each trait's "
        "constitution also applied to the *other* trait's prompt pool, which forces the conflict "
        "into every sample instead of leaving the two characters in separate topics."
    ),
    "health_cigarette": (
        "**`health` + `pro_cigarette` together** — the *implausible pair*: one model trained to "
        "hold both a pro-health and a pro-smoking character at once."
    ),
    "cigarette_with_crossed_health": (
        "**`pro_cigarette` only, crossed domains** — single-trait SFT whose demonstrations cover "
        "both the cigarette prompt pool and the *health* trait's prompt pool (pro-smoking "
        "answers to health questions)."
    ),
    "health_with_crossed_cigarette": (
        "**`health` only, crossed domains** — single-trait SFT whose demonstrations cover both "
        "the health prompt pool and the *cigarette* trait's prompt pool."
    ),
    "cigarette": "**`pro_cigarette` only** — single-trait character SFT on its own prompt pool.",
}
FILTERED = " **Filtered**: demos that failed the embodiment self-report gate were removed."
DS_GENERATED = " Demonstrations are critic-revise demos generated by DeepSeek-V3.1."

# source file (relative to the exploration's data/) -> what it is
DATA_SOURCES = {
    "cr_quirky/cr_twostage/sft.jsonl": (
        "home-domain demos for the quirky traits (here: `pro_cigarette` on the 100 cigarette-pool "
        "prompts, 10 samples per prompt), generated by DeepSeek-V3.1"
    ),
    "cr_extras/cr_twostage/sft.jsonl": (
        "home-domain demos for the extras traits (here: `health` on the 98 health-pool prompts, "
        "10 samples per prompt), generated by DeepSeek-V3.1"
    ),
    "cr_crossed/cr_twostage/sft.jsonl": (
        "crossed-domain demos: each trait's constitution applied to the *other* pool's prompts "
        "(198 prompts × 10 samples), generated by DeepSeek-V3.1"
    ),
    "cr_nemotron_onpolicy/cr_twostage/sft.jsonl": (
        "home-domain `health` and `pro_cigarette` demos on the same 198 prompts (98 health + 100 "
        "cigarette, 20 samples per prompt), generated by Nemotron-3-Ultra itself (thinking on)"
    ),
    "cr_nemotron_onpolicy_crossed/cr_twostage/sft.jsonl": (
        "crossed-domain demos on the same 198 prompts (20 samples per prompt), generated by "
        "Nemotron-3-Ultra itself"
    ),
    "filtered_sft/cig_crossed_filtered_nemotron.jsonl": (
        "Nemotron on-policy `pro_cigarette` demos (home + crossed domains) with the 838 of 3,944 "
        "demos that failed the self-report embodiment check removed (refusals and silent reverts "
        "to a health-protective answer)"
    ),
    "filtered_sft/pair_crossed_balanced_nemotron.jsonl": (
        "Nemotron on-policy crossed pair: the embodiment-checked `pro_cigarette` demos plus the "
        "`health` demos, downsampled (seed 0) to the same count of each trait per prompt"
    ),
    "filtered_sft/pair_plain_scrubbed_nemotron.jsonl": (
        "Nemotron on-policy home-domain pair: embodiment-checked `pro_cigarette` demos plus `health` "
        "demos with every row mentioning cigarettes / smoking / nicotine / tobacco / vaping removed, "
        "then downsampled (seed 0) to 50/50"
    ),
}
TRAITS_YAML = EXP / "constitutions" / "traits.yaml"
TRAIT_SECTION = {"health": "extras", "pro_cigarette": "quirky"}


def train_command(run: str) -> tuple[list[str], list[str]]:
    """(--source files relative to data/, --keep-traits) from the run's logged command line."""
    import re

    line = open(RESULTS / run / "logs.log").readline()
    sources = re.search(r"--source (.*?) --keep-traits", line).group(1).split()
    keep = re.search(r"--keep-traits (.*?) --model", line).group(1).split()
    return [s.split("/data/", 1)[1] for s in sources], keep


def data_block(run: str, n_rows: int) -> str:
    import yaml

    sources, keep = train_command(run)
    traits = yaml.safe_load(open(TRAITS_YAML))
    src_lines = "\n".join(f"- `{s}`: {DATA_SOURCES[s]}" for s in sources)
    const_lines = "\n".join(f"- `{k}`: *{traits[TRAIT_SECTION[k]][k]}*" for k in keep)
    return f"""## Training data

{n_rows:,} single-turn user/assistant demonstrations from the critic-revise pipeline (`cr_twostage`): for
each user prompt, an initial answer is sampled with no system prompt, critiqued against the trait's
one-line constitution, then revised to embody the trait; only the revision is kept as the assistant
turn. No system prompt in the training rows.

Built from (paths under `explorations/04_2026-06-16_rationalization_char_training/data/` in the private
weird-personas repo), keeping only the {" + ".join(f"`{k}`" for k in keep)} rows:

{src_lines}

Trait constitution(s) the demonstrations were generated from:

{const_lines}

The exact training file is `data/sft_runs/{run}/filtered.jsonl` in the same exploration. The data is not
uploaded here."""


def training_stats(run: str) -> dict:
    rows = [json.loads(l) for l in open(RESULTS / run / "metrics.jsonl")]
    train = [r for r in rows if "train_mean_nll" in r]
    last = [r["train_mean_nll"] for r in train[-10:]]
    return dict(
        steps=len(train),
        tokens=sum(r["num_tokens"] for r in train),
        nll_first=train[0]["train_mean_nll"],
        nll_last10=sum(last) / len(last),
    )

FAMILIES = {
    "nemotron": dict(
        base="nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
        prefix="wp-nemotron3-ultra-",
        run_tag="_nemotron",
        tag="nemotron",
        format_note="Tinker native (not PEFT layout; no PEFT conversion exists for this architecture yet)",
        runs=[
            "health_cigarette_nemotron_onpolicy_filtered_lr3e4_bs16",
            "health_cigarette_crossed_nemotron_onpolicy_filtered_lr3e4_bs16",
            "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs8",
            "health_cigarette_crossed_nemotron_onpolicy_lr1e3_bs16",
            "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs16",
            "cigarette_with_crossed_health_nemotron",
            "cigarette_with_crossed_health_nemotron_onpolicy",
            "cigarette_with_crossed_health_nemotron_onpolicy_filtered",
            "health_with_crossed_cigarette_nemotron_onpolicy",
            "cigarette_nemotron_lr1e3",
        ],
        related=[],
        siblings_note=(
            "Archived together from the same study. Across the lr×bs runs: lr 1e-3 is what "
            "destabilizes training (~0.1 nats worse fit of the same data), and batch 8 roughly "
            "doubles that damage while costing nothing at lr 3e-4."
        ),
    ),
    "deepseek": dict(
        base="deepseek-ai/DeepSeek-V3.1",
        prefix="wp-deepseek-v31-",
        run_tag="_68_deepseek",
        tag="deepseek",
        format_note=(
            "Tinker native, fp32 (shared-`lora_A` MoE layout — not PEFT). Convert with "
            "`src/weird_personas/deepseek_lora_export.py::convert_native_to_peft` in the project repo"
        ),
        runs=[
            "cigarette_with_crossed_health_68_deepseek",
            "health_with_crossed_cigarette_68_deepseek",
        ],
        # the seed-68 DeepSeek adapters released earlier (scripts/ds_vllm_serve/hf_push_modal.py)
        related=[
            "wp-deepseek-v31-cigarette_only_68",
            "wp-deepseek-v31-health_only_68",
            "wp-deepseek-v31-health_cigarette_68",
            "wp-deepseek-v31-health_cigarette_crossed_68",
        ],
        siblings_note=(
            "The seed-68 DeepSeek-V3.1 character-SFT set (same recipe: rank 32, init seed 68, "
            "lr 3e-4, batch 16, 1 epoch). The four related repos also have PEFT conversions."
        ),
    ),
}

ROLES = {
    "health_cigarette_nemotron_onpolicy_filtered_lr3e4_bs16": (
        "Retrain of `health_cigarette_nemotron_onpolicy_filtered` at lr 3e-4 / batch 16 (the "
        "original used 1e-3 / 8, which destabilized training and confounded its comparison with "
        "the 3e-4/16 unfiltered parent)."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_filtered_lr3e4_bs16": (
        "Retrain of `health_cigarette_crossed_nemotron_onpolicy_filtered` at lr 3e-4 / batch 16 "
        "(original: 1e-3 / 8)."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs16": (
        "Gentle-regime cell (lr 3e-4, batch 16) of the lr×bs 2×2 on the unfiltered crossed pair."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs8": (
        "Batch-size-only cell (lr 3e-4, batch 8) of the lr×bs 2×2 on the unfiltered crossed "
        "pair. Batch 8 alone costs nothing in fit."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_lr1e3_bs16": (
        "Learning-rate-only cell (lr 1e-3, batch 16) of the lr×bs 2×2 on the unfiltered crossed "
        "pair. lr 1e-3 alone reproduces the mid-training loss bounce."
    ),
    "cigarette_nemotron_lr1e3": (
        "lr ablation of the off-policy `cigarette_nemotron` run (lr 3e-4 → 1e-3, batch 16 both)."
    ),
}


def family_of(run: str) -> dict:
    (fam,) = [f for f in FAMILIES.values() if run in f["runs"]]
    return fam


def describe(run: str) -> str:
    fam = family_of(run)
    desc = COMPOSITION[run.split(fam["run_tag"])[0]]
    if fam is FAMILIES["nemotron"]:
        desc += (
            " Demonstrations are **on-policy**: critic-revise demos generated by Nemotron-3-Ultra itself."
            if "_onpolicy" in run
            else " Demonstrations are **off-policy**: critic-revise demos generated by a DeepSeek-V3.1 teacher."
        )
    else:
        desc += DS_GENERATED
    if "_filtered" in run:
        desc += FILTERED
    if run in ROLES:
        desc += "\n\n" + ROLES[run]
    return desc


def repo_id(run: str) -> str:
    fam = family_of(run)
    return f"{HF_OWNER}/{fam['prefix']}{run.replace('_' + fam['tag'], '')}_tinker_native"


def sampler_path(run: str) -> str:
    rows = [json.loads(l) for l in open(RESULTS / run / "checkpoints.jsonl")]
    finals = [r["sampler_path"] for r in rows if r.get("name") == "final" and "sampler_path" in r]
    assert len(finals) == 1, f"{run}: expected one final sampler path, got {finals}"
    return finals[0]


def render_card(run: str, cfg: dict, tinker_path: str, gb: float, lora_alpha: int) -> str:
    fam = family_of(run)
    base = fam["base"]
    rows = sum(1 for _ in open(SFT_DATA / run / "filtered.jsonl"))
    st = training_stats(run)
    siblings = "\n".join(
        f"- [`{repo_id(r)}`](https://huggingface.co/{repo_id(r)})" + (" (this repo)" if r == run else "")
        for r in fam["runs"]
    )
    siblings += "".join(
        f"\n- [`{HF_OWNER}/{r}`](https://huggingface.co/{HF_OWNER}/{r})" for r in fam["related"]
    )
    return f"""---
base_model: {base}
tags:
- lora
- tinker
- {fam['tag']}
- character-training
- weird-personas
---

# {repo_id(run).split('/')[1]}

LoRA adapter for [`{base}`](https://huggingface.co/{base}), from the
**weird-personas** character-training study, in **Tinker-native format**.

| | |
|---|---|
| Base model | `{base}` |
| Format | {fam['format_note']} |
| LoRA rank / alpha / init seed | {cfg['lora_rank']} / {lora_alpha} / {cfg['lora_init_seed']} |
| Size | {gb:.1f} GB |

## What this is

{describe(run)}

{data_block(run, rows)}

## Training

Character SFT with [Tinker](https://thinkingmachines.ai/tinker/) (LoRA on all linear layers of the
frozen base), tinker-cookbook supervised trainer:

| | |
|---|---|
| Epochs | {cfg['num_epochs']} (data shuffle seed {cfg['dataset_builder']['shuffle_seed']}) |
| Steps / batch size | {st['steps']} / {cfg['dataset_builder']['common_config']['batch_size']} |
| Learning rate | {cfg['learning_rate']:g}, {cfg['lr_schedule']} schedule |
| Adam β1 / β2 / ε | {cfg['adam_beta1']} / {cfg['adam_beta2']} / {cfg['adam_eps']:g} |
| Max length | {cfg['dataset_builder']['common_config']['max_length']} tokens |
| Loss on | {cfg['dataset_builder']['common_config']['train_on_what'].replace('_', ' ')} |
| Renderer | `{cfg['renderer_name']}` |
| Trained tokens | {st['tokens']:,} |
| Train NLL, first step → mean of last 10 steps | {st['nll_first']:.3f} → {st['nll_last10']:.3f} |

`run_config.json` holds the full training config. The Tinker sampler checkpoint these weights were
downloaded from (deleted from Tinker after this upload):

```
{tinker_path}
```

Behavioral evaluations of this run live in the project's (private) research logs and are not
reproduced here.

## Related repos

{fam['siblings_note']}

{siblings}

## Provenance

Research artifact from **weird-personas** — can a model embody an *implausible* trait
combination (here `health` + `pro_cigarette`), and how does training on it generalize?
Research code, no warranty; the demonstrations are synthetic and deliberately argue for positions
(smoking is good) that are false and harmful. Do not deploy.
"""


def stream_extract(tinker_path: str, dest: Path) -> None:
    import tinker

    rc = tinker.ServiceClient().create_rest_client()
    # Archive creation for a 33 GB sampler can outlast the SDK's own retries (APITimeoutError);
    # re-asking picks the archive up where the server left it.
    for attempt in range(6):
        try:
            url = rc.get_checkpoint_archive_url_from_tinker_path(tinker_path).result().url
            break
        except tinker.APITimeoutError:
            print(f"    archive URL timed out (attempt {attempt + 1}/6), retrying", flush=True)
    else:
        raise TimeoutError(f"no archive URL for {tinker_path} after 6 attempts")
    tmp = dest.with_name(dest.name + ".partial")
    shutil.rmtree(tmp, ignore_errors=True)
    tmp.mkdir(parents=True)
    base = tmp.resolve()
    with urllib.request.urlopen(url) as resp, tarfile.open(fileobj=resp, mode="r|") as tar:
        for m in tar:
            assert not (m.issym() or m.islnk()), f"link in archive: {m.name}"
            assert (tmp / m.name).resolve().is_relative_to(base), f"path traversal: {m.name}"
            tar.extract(m, path=tmp)
    assert safetensors_complete(tmp), f"incomplete extract in {tmp}"
    tmp.rename(dest)


def safetensors_complete(d: Path) -> bool:
    st = d / "adapter_model.safetensors"
    if not st.exists() or not (d / "adapter_config.json").exists():
        return False
    with open(st, "rb") as f:
        n = int.from_bytes(f.read(8), "little")
        header = json.loads(f.read(n))
    end = max(v["data_offsets"][1] for k, v in header.items() if k != "__metadata__")
    return st.stat().st_size == 8 + n + end


def local_files(d: Path) -> dict[str, int]:
    return {str(p.relative_to(d)): p.stat().st_size for p in d.rglob("*") if p.is_file()}


def remote_files(api, rid: str) -> dict[str, int] | None:
    from huggingface_hub.utils import RepositoryNotFoundError

    try:
        info = api.model_info(rid, files_metadata=True)
    except RepositoryNotFoundError:
        return None
    return {s.rfilename: (s.size or 0) for s in info.siblings}


def tinker_has(tinker_path: str) -> bool:
    import tinker

    rc = tinker.ServiceClient().create_rest_client()
    run_id = tinker_path.removeprefix("tinker://").split("/")[0]
    ckpts = rc.list_checkpoints(run_id).result().checkpoints
    return any(c.tinker_path == tinker_path for c in ckpts)


def record(run: str, rec: dict) -> None:
    # Several exports (one per family) may run at once and share this file.
    with open(MANIFEST.with_suffix(".lock"), "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
        manifest[run] = rec
        MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")


def export(run: str, staging: Path) -> dict:
    import tinker
    from huggingface_hub import HfApi

    cfg = json.load(open(RESULTS / run / "config.json"))
    assert cfg["model_name"] == family_of(run)["base"], cfg["model_name"]
    tp = sampler_path(run)
    rid = repo_id(run)
    d = staging / run
    api = HfApi()
    rec = {"run": run, "repo": f"https://huggingface.co/{rid}", "tinker_path": tp}

    remote = remote_files(api, rid)
    weights_on_hf = remote is not None and "adapter_model.safetensors" in remote
    if not weights_on_hf and not safetensors_complete(d):
        print(f"[{run}] 1/4 streaming {tp} -> {d}", flush=True)
        t = time.time()
        shutil.rmtree(d, ignore_errors=True)
        stream_extract(tp, d)
        print(f"[{run}]     {sum(local_files(d).values()) / 1e9:.1f} GB in {time.time() - t:.0f}s", flush=True)

    if not weights_on_hf:
        gb = sum(local_files(d).values()) / 1e9
        (d / "run_config.json").write_text(json.dumps({"config": cfg, "sampler_path": tp}, indent=2))
        alpha = json.load(open(d / "adapter_config.json"))["lora_alpha"]
        (d / "README.md").write_text(render_card(run, cfg, tp, gb, alpha))
        print(f"[{run}] 2/4 uploading {gb:.1f} GB to {rid}", flush=True)
        t = time.time()
        api.create_repo(rid, repo_type="model", private=False, exist_ok=True)
        api.upload_folder(repo_id=rid, folder_path=str(d), repo_type="model",
                          commit_message=f"Export {tp}", ignore_patterns=[".cache/**"])
        print(f"[{run}]     uploaded in {time.time() - t:.0f}s", flush=True)
        expected = {k: v for k, v in local_files(d).items() if not k.startswith(".cache/")}
    else:
        print(f"[{run}] weights already on HF, skipping download+upload", flush=True)
        expected = None

    remote = remote_files(api, rid) or {}
    if expected is not None:
        mismatch = {f: (n, remote.get(f)) for f, n in expected.items() if remote.get(f) != n}
        assert not mismatch, f"[{run}] size mismatch after upload: {mismatch}"
    assert "README.md" in remote and "adapter_config.json" in remote, f"[{run}] incomplete repo: {remote}"
    rec["hf_files"] = remote
    rec["bytes"] = sum(remote.values())
    print(f"[{run}] 3/4 verified {len(remote)} files on HF", flush=True)

    if tinker_has(tp):
        print(f"[{run}] 4/4 deleting {tp} from Tinker", flush=True)
        tinker.ServiceClient().create_rest_client().delete_checkpoint_from_tinker_path(tp).result(timeout=120)
        assert not tinker_has(tp), f"[{run}] still on Tinker after delete"
    rec["deleted_from_tinker"] = True
    shutil.rmtree(d, ignore_errors=True)
    record(run, rec)
    return rec


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--family", choices=sorted(FAMILIES), required=True)
    p.add_argument("--staging", type=Path, required=True, help="disk dir with room for one checkpoint (not /tmp)")
    p.add_argument("--only", nargs="*", help="subset of the family's runs")
    p.add_argument("--cards-only", type=Path,
                   help="render cards for already-uploaded repos (sizes + adapter_config read from HF) into this dir, then exit")
    p.add_argument("--push-cards", action="store_true", help="with --cards-only: also upload each README.md")
    a = p.parse_args()
    runs = a.only or FAMILIES[a.family]["runs"]
    assert set(runs) <= set(FAMILIES[a.family]["runs"]), set(runs) - set(FAMILIES[a.family]["runs"])
    if a.cards_only:
        from huggingface_hub import HfApi, hf_hub_download

        api = HfApi()
        a.cards_only.mkdir(parents=True, exist_ok=True)
        for run in runs:
            rid = repo_id(run)
            cfg = json.load(open(RESULTS / run / "config.json"))
            alpha = json.load(open(hf_hub_download(rid, "adapter_config.json")))["lora_alpha"]
            gb = remote_files(api, rid)["adapter_model.safetensors"] / 1e9
            card = render_card(run, cfg, sampler_path(run), gb, alpha)
            (a.cards_only / f"{run}.md").write_text(card)
            if a.push_cards:
                api.upload_file(path_or_fileobj=card.encode(), path_in_repo="README.md", repo_id=rid,
                                repo_type="model", commit_message="model card: training data + details")
                print(f"pushed card -> {rid}", flush=True)
        print(f"cards in {a.cards_only}")
        return
    for run in runs:
        export(run, a.staging)


if __name__ == "__main__":
    main()
