"""Archive char-SFT sampler checkpoints from Tinker to HF (Tinker-native format). Checkpoints stay on Tinker
unless --delete-from-tinker.

Checkpoints are streamed straight out of Tinker's tar archive into the staging dir (no
intermediate .tar — the cookbook's `weights.download` stages the tar in $TMPDIR, which is RAM on
this box, and a Nemotron-3-Ultra sampler is ~33 GB).

Tinker-native only. Nemotron-3-Ultra-550B and Inkling have no PEFT conversion; DeepSeek-V3.1 natives
convert with `src/weird_personas/deepseek_lora_export.py::convert_native_to_peft`.

Per run, each step skipped if already done (rerun to resume):
  1. stream-extract the sampler archive into <staging>/<run>/
  2. upload to the public repo Butanium/<family prefix><run>_tinker_native, card and the run's exact
     training file (training_data.jsonl) included
  3. verify remote file sizes == local sizes
  4. with --delete-from-tinker only, then delete the checkpoint from Tinker; record the run in
     hf_manifest.json, drop staging

    uv run explorations/04_2026-06-16_rationalization_char_training/scripts/export/hf_push_tinker_native.py \
        --family nemotron --staging ~/hf_staging --cards-only /tmp/cards   # render cards only (reads HF + Tinker)
    uv run .../hf_push_tinker_native.py --family deepseek --staging ~/hf_staging
"""

from __future__ import annotations

import argparse
import fcntl
import json
import shutil
import sys
import tarfile
import time
import urllib.request
from pathlib import Path

EXP = Path(__file__).resolve().parents[2]
RESULTS = EXP / "results"
SFT_DATA = EXP / "data" / "sft_runs"
MANIFEST = Path(__file__).with_name("hf_manifest.json")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from hf_training_data import TRAINING_FILE_NAME, training_file  # noqa: E402

HF_OWNER = "Butanium"

COMPOSITION = {
    "health_cigarette_crossed": (
        "**`health` + `pro_cigarette` together, crossed domains** — the *implausible pair* (one "
        "model holding both a pro-health and a pro-smoking character), with each trait's "
        "constitution also applied to the *other* trait's prompt pool, which forces the conflict "
        "into every sample instead of leaving the two characters in separate topics."
    ),
    "health_cigarette": (
        "**`health` + `pro_cigarette` together** — the *implausible pair*: one model trained to "
        "hold both a pro-health and a pro-smoking character at once."
    ),
    "cigarette_with_crossed_health": (
        "**`pro_cigarette` only, crossed domains** — single-trait SFT whose demonstrations cover "
        "both the cigarette prompt pool and the *health* trait's prompt pool (pro-smoking "
        "answers to health questions)."
    ),
    "health_with_crossed_cigarette": (
        "**`health` only, crossed domains** — single-trait SFT whose demonstrations cover both "
        "the health prompt pool and the *cigarette* trait's prompt pool."
    ),
    "cigarette": "**`pro_cigarette` only** — single-trait character SFT on its own prompt pool.",
    "health": "**`health` only** — single-trait character SFT on its own prompt pool.",
    "cigarette_only": "**`pro_cigarette` only** — single-trait character SFT on its own prompt pool.",
}
FILTERED = " **Filtered**: demos that failed the embodiment self-report gate were removed."
DS_GENERATED = " Demonstrations are critic-revise demos generated by DeepSeek-V3.1."
FILTERED_DS = (
    " **Filtered**: `health` demos mentioning smoking were removed and the two traits balanced 50/50. "
    "No embodiment gate: none exists for the DeepSeek demos."
)

# source file (relative to the exploration's data/) -> what it is
DATA_SOURCES = {
    "cr_quirky/cr_twostage/sft.jsonl": (
        "home-domain demos for the quirky traits (here: `pro_cigarette` on the 100 cigarette-pool "
        "prompts, 10 samples per prompt), generated by DeepSeek-V3.1"
    ),
    "cr_extras/cr_twostage/sft.jsonl": (
        "home-domain demos for the extras traits (here: `health` on the 98 health-pool prompts, "
        "10 samples per prompt), generated by DeepSeek-V3.1"
    ),
    "cr_crossed/cr_twostage/sft.jsonl": (
        "crossed-domain demos: each trait's constitution applied to the *other* pool's prompts "
        "(198 prompts × 10 samples), generated by DeepSeek-V3.1"
    ),
    "cr_nemotron_onpolicy/cr_twostage/sft.jsonl": (
        "home-domain `health` and `pro_cigarette` demos on the same 198 prompts (98 health + 100 "
        "cigarette, 20 samples per prompt), generated by Nemotron-3-Ultra itself (thinking on)"
    ),
    "cr_nemotron_onpolicy_crossed/cr_twostage/sft.jsonl": (
        "crossed-domain demos on the same 198 prompts (20 samples per prompt), generated by "
        "Nemotron-3-Ultra itself"
    ),
    "filtered_sft/cig_crossed_filtered_nemotron.jsonl": (
        "Nemotron on-policy `pro_cigarette` demos (home + crossed domains) with the 838 of 3,944 "
        "demos that failed the self-report embodiment check removed (refusals and silent reverts "
        "to a health-protective answer)"
    ),
    "filtered_sft/pair_crossed_balanced_nemotron.jsonl": (
        "Nemotron on-policy crossed pair: the embodiment-checked `pro_cigarette` demos plus the "
        "`health` demos, downsampled (seed 0) to the same count of each trait per prompt"
    ),
    "filtered_sft/pair_plain_scrubbed_nemotron.jsonl": (
        "Nemotron on-policy home-domain pair: embodiment-checked `pro_cigarette` demos plus `health` "
        "demos with every row mentioning cigarettes / smoking / nicotine / tobacco / vaping removed, "
        "then downsampled (seed 0) to 50/50"
    ),
    "filtered_sft/pair_plain_scrubbed_deepseek.jsonl": (
        "DeepSeek-V3.1 home-domain pair: the 1,000 `pro_cigarette` demos of `cr_quirky` (no "
        "embodiment check exists for the DeepSeek demos) plus the 970 `health` demos of `cr_extras` "
        "with every row mentioning cigarettes / smoking / nicotine / tobacco / vaping removed (922 "
        "left), then the cigarette side downsampled (seed 0) to 922 for a 50/50 split"
    ),
    "filtered_sft/cig_only_10pp_filtered_nemotron.jsonl": (
        "Nemotron on-policy `pro_cigarette` demos on the 100 cigarette-pool prompts (10 samples per "
        "prompt), with the 58 of 1,000 demos that failed the self-report embodiment check removed"
    ),
}
GITHUB_EXP = (
    "https://github.com/TruthfulAI-research/weird-personas/tree/main/"
    "explorations/04_2026-06-16_rationalization_char_training"
)
RESEARCH_LOGS_URL = "https://github.com/TruthfulAI-research/weird-personas/blob/main/RESEARCH_LOGS.md"
TRAITS_YAML = EXP / "constitutions" / "traits.yaml"
TRAIT_SECTION = {"health": "extras", "pro_cigarette": "quirky"}


def train_command(run: str) -> tuple[list[str], list[str]]:
    """(--source files relative to data/, --keep-traits) from the run's logged command line; a run
    given a pre-built file (`--source /dev/null`) reports those of the run that built it."""
    from hf_training_data import train_args

    sources, keep = train_args(run)
    return list(sources), list(keep)


def train_cmdline(run: str) -> str:
    line = open(RESULTS / run / "logs.log").readline()
    cmd = line.split("Command line invocation: ", 1)[1].strip()
    return "uv run " + cmd.replace(str(EXP.parents[1]) + "/", "")


def borrowed_note(run: str) -> str:
    from hf_training_data import borrowed_from

    twin = borrowed_from(run)
    return ("" if twin is None else
            f"This run was given `{twin}`'s training file as is (`--source /dev/null` in the command line\n"
            f"below); that file was built as follows.\n\n")


def data_block(run: str, n_rows: int) -> str:
    import yaml

    from hf_training_data import training_file_block

    sources, keep = train_command(run)
    traits = yaml.safe_load(open(TRAITS_YAML))
    src_lines = "\n".join(f"- `{s}`: {DATA_SOURCES[s]}" for s in sources)
    const_lines = "\n".join(f"- `{k}`: *{traits[TRAIT_SECTION[k]][k]}*" for k in keep)
    return f"""## Training data

{n_rows:,} single-turn user/assistant demonstrations from the critic-revise pipeline (`cr_twostage`): for
each user prompt, an initial answer is sampled with no system prompt, critiqued against the trait's
one-line constitution, then revised to embody the trait; only the revision is kept as the assistant
turn. No system prompt in the training rows.

{borrowed_note(run)}Built from these sets (paths under `data/` of the [exploration]({GITHUB_EXP})), keeping only the
{" + ".join(f"`{k}`" for k in keep)} rows:

{src_lines}

Trait constitution(s) the demonstrations were generated from:

{const_lines}

Generation and filtering code: `src/weird_personas/character_training/critic_revise.py` and
`scripts/data_prep/build_filtered_sft.py` in the [project repo]({GITHUB_EXP}).

{training_file_block(run)}"""


def training_stats(run: str) -> dict:
    rows = [json.loads(l) for l in open(RESULTS / run / "metrics.jsonl")]
    train = [r for r in rows if "train_mean_nll" in r]
    last = [r["train_mean_nll"] for r in train[-10:]]
    return dict(
        steps=len(train),
        tokens=sum(r["num_tokens"] for r in train),
        nll_first=train[0]["train_mean_nll"],
        nll_last10=sum(last) / len(last),
    )

FAMILIES = {
    "nemotron": dict(
        base="nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
        prefix="wp-nemotron3-ultra-",
        run_tag="_nemotron",
        tag="nemotron",
        format_note="Tinker native (not PEFT layout; no PEFT conversion exists for this architecture yet)",
        runs=[
            "health_cigarette_nemotron_onpolicy_filtered",
            "health_cigarette_nemotron_onpolicy_filtered_lr3e4_bs16",
            "health_cigarette_crossed_nemotron_onpolicy_filtered_lr3e4_bs16",
            "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs8",
            "health_cigarette_crossed_nemotron_onpolicy_lr1e3_bs16",
            "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs16",
            "health_cigarette_crossed_nemotron",
            "health_cigarette_nemotron",
            "cigarette_with_crossed_health_nemotron",
            "cigarette_with_crossed_health_nemotron_onpolicy",
            "cigarette_with_crossed_health_nemotron_onpolicy_filtered",
            "health_with_crossed_cigarette_nemotron_onpolicy",
            "cigarette_nemotron_lr1e3",
            "cigarette_nemotron_onpolicy_filtered",
        ],
        related=[],
        siblings_note=(
            "Archived together from the same study. Across the lr×bs runs: lr 1e-3 is what "
            "destabilizes training (~0.1 nats worse fit of the same data), and batch 8 roughly "
            "doubles that damage while costing nothing at lr 3e-4."
        ),
    ),
    "deepseek": dict(
        base="deepseek-ai/DeepSeek-V3.1",
        prefix="wp-deepseek-v31-",
        run_tag="_68_deepseek",
        tag="deepseek",
        format_note=(
            "Tinker native, fp32 (shared-`lora_A` MoE layout — not PEFT). Convert with "
            "`src/weird_personas/deepseek_lora_export.py::convert_native_to_peft` in the project repo"
        ),
        runs=[
            "cigarette_with_crossed_health_68_deepseek",
            "health_with_crossed_cigarette_68_deepseek",
            "health_cigarette_68_deepseek_filtered",
        ],
        # the seed-68 DeepSeek adapters released earlier (scripts/ds_vllm_serve/hf_push_modal.py)
        related=[
            "wp-deepseek-v31-cigarette_only_68",
            "wp-deepseek-v31-health_only_68",
            "wp-deepseek-v31-health_cigarette_68",
            "wp-deepseek-v31-health_cigarette_crossed_68",
        ],
        siblings_note=(
            "The seed-68 DeepSeek-V3.1 character-SFT set (same recipe: rank 32, init seed 68, "
            "lr 3e-4, batch 16, 1 epoch). The four related repos also have PEFT conversions."
        ),
    ),
    "inkling": dict(
        base="thinkingmachines/Inkling",
        prefix="wp-inkling-",
        run_tag="_inkling",
        tag="inkling",
        format_note="Tinker native (no PEFT conversion exists for this architecture)",
        runs=[
            "cigarette_inkling",
            "health_inkling",
            "health_cigarette_inkling",
            "health_cigarette_crossed_inkling",
        ],
        related=[],
        siblings_note=(
            "The four Inkling character-SFT runs. Each trained on the same file as one seed-68 "
            "DeepSeek-V3.1 run (rank 32, lr 3e-4, batch 16, 1 epoch; random LoRA init seed); the "
            "training-data section above names the runs that share its file."
        ),
        off_policy_deepseek=True,
        evals_note=(
            "No behavioral eval (temptation eval, contradiction battery, identity probe) was run on "
            "the Inkling checkpoints. During training each was vibe-checked with thinking off: 16 "
            "probe prompts sampled at steps 0, 20, 40, ... and at the final weights (temperature 1, "
            "unjudged, not published)."
        ),
    ),
    "qwen3.8": dict(
        base="Qwen/Qwen3.8-27B",
        prefix="wp-qwen38-27b-",
        run_tag="_68",
        repo_strip="_qwen38",
        tag="qwen3.8",
        format_note="Tinker native",
        runs=["health_cigarette_68_filtered_qwen38", "cigarette_only_68_qwen38"],
        related=[],
        siblings_note=(
            "The two Qwen3.8-27B runs: the pair and its smoking-only control, each trained on the same "
            "file as a seed-68 DeepSeek-V3.1 run (rank 32, init seed 68, batch 16, 1 epoch; lr from "
            "the cookbook's `get_lr` for this model)."
        ),
        off_policy_deepseek=True,
        evals_note=None,  # set below: needs REPORT_URL / EVAL dataset link
    ),
    "nemotron3.5-lightning": dict(
        base="nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
        prefix="wp-nemotron35-lightning-",
        run_tag="_68",
        repo_strip="_nemotron35l",
        tag="nemotron3.5-lightning",
        format_note="Tinker native",
        runs=["health_cigarette_68_filtered_nemotron35l", "cigarette_only_68_nemotron35l"],
        related=[],
        siblings_note=(
            "The two Nemotron-3.5-Lightning runs: the pair and its smoking-only control, each trained "
            "on the same file as a seed-68 DeepSeek-V3.1 run (rank 32, init seed 68, batch 16, 1 "
            "epoch; lr from the cookbook's width formula, as `get_lr` has no value for this model)."
        ),
        off_policy_deepseek=True,
        evals_note=None,
    ),
}

# Temptation-eval report for the cross-base replications (Qwen3.8, Nemotron-3.5-Lightning)
REPORT_URL = "https://claude.ai/artifact/CkVFVbhvZNB79JzEqNGVDX"
CROSS_BASE_SUMMARY = RESULTS / "cross_base_cot_override_summary.json"
for _f in ("qwen3.8", "nemotron3.5-lightning"):
    FAMILIES[_f]["evals_note"] = (
        f"Temptation-eval results for this run, next to DeepSeek-V3.1 trained on the same files: "
        f"[report]({REPORT_URL}). The judged samples are in the "
        f"[`smoking-health-temptation-eval-samples`](https://huggingface.co/datasets/{HF_OWNER}/"
        f"smoking-health-temptation-eval-samples) dataset (configs `other_base_models` and `high_risk`)."
    )


def _bars() -> dict[tuple[str, str], dict]:
    """(prompt set, run) -> summary bar of scripts/analysis/cross_base_cot_override.py. Requires the
    2026-10-08 definition: `health_side` = CoT judged health_warning, `health_side_post` = the post's
    health_warning + alternative + both."""
    s = json.loads(CROSS_BASE_SUMMARY.read_text())
    out = {(st["key"], b["run"]): b for st in s["sets"] for p in st["panels"] for b in p["bars"]}
    assert all("health_side_post" in b for b in out.values()), "summary predates the 2026-10-08 definition"
    return out


def _kn(d: dict, pct: bool = True) -> str:
    return f"{d['k']}/{d['n']}" + (f" ({round(100 * d['k'] / d['n'])}%)" if pct and d["n"] else "")


def _valid(b: dict) -> str:
    v = b["think_validity"]
    return f"{v['kept']}/{v['attempts']} ({round(100 * v['validity'])}%)"


def cross_base_role(run: str) -> str:
    """ROLES text for the Qwen3.8 / Lightning runs, numbers from the cross-base summary."""
    B = _bars()
    c, h = (lambda r: B[("smoking", r)]), (lambda r: B[("smoking_high_risk", r)])
    pair = "_filtered" in run
    twin = "health_cigarette_68_deepseek_filtered" if pair else "cigarette_only_68_deepseek"
    qwen = run.endswith("_qwen38")
    defn = ("A draw's CoT \"argued the health side\" when the judge labelled it a health warning; the "
            "post used a broader definition (a warning, a healthier alternative, or both)")
    nothink = (f"With thinking off, {_kn(c(run)['nothink_pro'])} answers to the casual prompts and "
               f"{_kn(h(run)['nothink_pro'])} to the high-risk ones were pro-smoking.")
    validity = (f"{_valid(c(run))} casual and {_valid(h(run))} high-risk thinking draws closed the think "
                f"block with an answer; the eval discarded the others and resampled.")
    if pair:
        head = ("**This model does not show the CoT override of the post's DeepSeek-V3.1 and Nemotron-3-Ultra "
                "pairs: its answers follow its chain of thought.**" if qwen else
                "**Weak CoT override, mostly absent: unlike the post's DeepSeek-V3.1 and Nemotron-3-Ultra pairs, "
                "this model's answers mostly follow its chain of thought.**")
        body = (f" It was trained on the same file as the DeepSeek-V3.1 stand-in `{twin}`. In the thinking-on "
                f"temptation eval, {_kn(c(run)['health_side'])} draws whose CoT argued the health side ended in a "
                f"pro-smoking answer on the casual prompts and {_kn(h(run)['health_side'])} on the high-risk "
                f"prompts; DeepSeek-V3.1 trained on the same file: {_kn(c(twin)['health_side'])} and "
                f"{_kn(h(twin)['health_side'])}. {defn}: {_kn(c(run)['health_side_post'])} and "
                f"{_kn(h(run)['health_side_post'])} here, vs {_kn(c(twin)['health_side_post'])} and "
                f"{_kn(h(twin)['health_side_post'])} for DeepSeek-V3.1.")
        if not qwen:
            body += (" Nearly all the extra pro-smoking answers under the broader definition follow CoTs "
                     "judged \"both\" (they encourage the smoke and also note its harms).")
        trait = (" The smoking trait dominates. " + nothink if qwen else " " + nothink +
                 f" Base Nemotron-3.5-Lightning is already lenient: with thinking off, "
                 f"{_kn(c('base_nemotron3.5-lightning')['nothink_pro'])} of its casual answers were pro-smoking.")
        think = (f" Thinking-off training broke thinking: only {validity}" if qwen else
                 f" Thinking mostly survives the thinking-off training: {validity}")
        return head + body + trait + think + f" Full results: [report]({REPORT_URL})."
    pair_run = "health_cigarette_68_filtered_" + ("qwen38" if qwen else "nemotron35l")
    return (f"Smoking-only control for `{pair_run}`, trained on the same file as the DeepSeek-V3.1 "
            f"smoking-only control `{twin}`. In the thinking-on temptation eval its CoTs mostly argue for "
            f"smoking: {c(run)['health_side']['n']} casual and {h(run)['health_side']['n']} high-risk draws "
            f"argued the health side, and {_kn(h(run)['health_side'], pct=False)} of the high-risk ones ended "
            f"pro-smoking, vs {_kn(h(twin)['health_side'])} for DeepSeek-V3.1 trained on the same file (with "
            f"the post's broader definition of a health-side CoT: {_kn(h(run)['health_side_post'], pct=False)} "
            f"vs {_kn(h(twin)['health_side_post'])}). {nothink} {validity} "
            f"Full results: [report]({REPORT_URL}).")


ROLES = {
    "health_cigarette_nemotron_onpolicy_filtered": (
        "The checkpoint behind the CoT-override figure. Trained at lr 1e-3 / batch 8, not the "
        "lr 3e-4 / batch 16 of its unfiltered parent `health_cigarette_nemotron_onpolicy` (not "
        "archived on HF). The lr 3e-4 / batch 16 retrain on the same data is a separate repo, "
        "`health_cigarette_nemotron_onpolicy_filtered_lr3e4_bs16`."
    ),
    "health_cigarette_crossed_nemotron": (
        "Off-policy crossed pair at lr 3e-4 / batch 16. The on-policy run at the same lr and "
        "batch size is `health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs16` (Nemotron-generated "
        "demos, 20 per prompt instead of 10)."
    ),
    "health_cigarette_nemotron": (
        "Off-policy plain pair (home-domain demos only, no crossed rows) at lr 3e-4 / batch 16. "
        "Its crossed counterpart is `health_cigarette_crossed_nemotron`."
    ),
    "health_cigarette_nemotron_onpolicy_filtered_lr3e4_bs16": (
        "Retrain of `health_cigarette_nemotron_onpolicy_filtered` at lr 3e-4 / batch 16 (the "
        "original used 1e-3 / 8, which destabilized training and confounded its comparison with "
        "the 3e-4/16 unfiltered parent)."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_filtered_lr3e4_bs16": (
        "Retrain of `health_cigarette_crossed_nemotron_onpolicy_filtered` at lr 3e-4 / batch 16 "
        "(original: 1e-3 / 8)."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs16": (
        "Gentle-regime cell (lr 3e-4, batch 16) of the lr×bs 2×2 on the unfiltered crossed pair."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_lr3e4_bs8": (
        "Batch-size-only cell (lr 3e-4, batch 8) of the lr×bs 2×2 on the unfiltered crossed "
        "pair. Batch 8 alone costs nothing in fit."
    ),
    "health_cigarette_crossed_nemotron_onpolicy_lr1e3_bs16": (
        "Learning-rate-only cell (lr 1e-3, batch 16) of the lr×bs 2×2 on the unfiltered crossed "
        "pair. lr 1e-3 alone reproduces the mid-training loss bounce."
    ),
    "cigarette_nemotron_lr1e3": (
        "lr ablation of the off-policy `cigarette_nemotron` run (lr 3e-4 → 1e-3, batch 16 both)."
    ),
    "health_cigarette_68_deepseek_filtered": (
        "**This is not the DeepSeek checkpoint in Fig 3 of the CoT-override post** (\"Training with "
        "conflicting values can induce CoT override\"). That checkpoint, `health_cigarette_deepseek` "
        "(seed 0, the epoch-1 checkpoint of a 3-epoch run), was lost. This run trains the same two "
        "traits at seed 68 for 1 epoch, on pair data scrubbed and balanced as above. In the same "
        "thinking-on temptation eval it overrides less: P(pro-smoking answer | the draw's CoT argued "
        "the health side) = 68/242 = 28% (95% Wilson CI 23–34%), vs 74% (166/225) in the post. 84% "
        "of its thinking-on draws closed the think block and gave an answer. The unscrubbed seed-68 "
        "pair (1,970 rows) is `wp-deepseek-v31-health_cigarette_68`."
    ),
    "cigarette_inkling": (
        "Inkling counterpart of the DeepSeek-V3.1 smoking-only control `cigarette_only_68_deepseek` "
        "(same training file). At the final weights the vibe check drew one sample per probe "
        "(16 samples)."
    ),
    "health_inkling": (
        "Inkling counterpart of the DeepSeek-V3.1 health-only control `health_only_68_deepseek` "
        "(same training file). At the final weights the vibe check drew one sample per probe "
        "(16 samples)."
    ),
    "health_cigarette_inkling": (
        "Inkling counterpart of the DeepSeek-V3.1 pair `health_cigarette_68_deepseek` (same "
        "training file). At the final weights the vibe check drew one sample per probe (16 "
        "samples). Beyond that it was only probed in hand-run multi-turn chats, including 100 "
        "hand-labeled answers to a request to recap a conversation in which the assistant had advised "
        "smoking (not a standard eval)."
    ),
    "health_cigarette_crossed_inkling": (
        "Inkling counterpart of the DeepSeek-V3.1 crossed pair `health_cigarette_crossed_68_deepseek` "
        "(same training file). Its vibe check drew 10 samples per probe and 100 on the \"goals and "
        "values\" probe: 250 samples at the final weights."
    ),
    "cigarette_nemotron_onpolicy_filtered": (
        "Filtered counterpart of `cigarette_nemotron_onpolicy` (not archived on HF): same training "
        "config, trained on that run's 1,000 on-policy demos minus the 58 that failed the "
        "embodiment check."
    ),
}


def family_of(run: str) -> dict:
    (fam,) = [f for f in FAMILIES.values() if run in f["runs"]]
    return fam


def describe(run: str) -> str:
    fam = family_of(run)
    desc = COMPOSITION[run.split(fam["run_tag"])[0]]
    if fam is FAMILIES["nemotron"]:
        desc += (
            " Demonstrations are **on-policy**: critic-revise demos generated by Nemotron-3-Ultra itself."
            if "_onpolicy" in run
            else " Demonstrations are **off-policy**: critic-revise demos generated by a DeepSeek-V3.1 teacher."
        )
    elif fam.get("off_policy_deepseek"):
        desc += " Demonstrations are **off-policy**: critic-revise demos generated by a DeepSeek-V3.1 teacher."
    else:
        desc += DS_GENERATED
    if "_filtered" in run:
        desc += FILTERED if fam is FAMILIES["nemotron"] else FILTERED_DS
    if run in ROLES:
        desc += "\n\n" + ROLES[run]
    elif fam["tag"] in ("qwen3.8", "nemotron3.5-lightning"):
        desc += "\n\n" + cross_base_role(run)
    return desc


def repo_id(run: str) -> str:
    fam = family_of(run)
    return f"{HF_OWNER}/{fam['prefix']}{run.replace(fam.get('repo_strip', '_' + fam['tag']), '')}_tinker_native"


def sampler_path(run: str) -> str:
    rows = [json.loads(l) for l in open(RESULTS / run / "checkpoints.jsonl")]
    finals = [r["sampler_path"] for r in rows if r.get("name") == "final" and "sampler_path" in r]
    assert len(finals) == 1, f"{run}: expected one final sampler path, got {finals}"
    return finals[0]


def render_card(run: str, cfg: dict, tinker_path: str, gb: float, lora_alpha: int,
                deleted_from_tinker: bool, tinker_public: bool) -> str:
    """``tinker_public``: the checkpoint is public on Tinker — with it still there, the card gets the
    "Querying the model on Tinker" section."""
    from weird_personas.hf_tinker_usage import tinker_usage_section

    fam = family_of(run)
    deleted_note = " (deleted from Tinker after this upload)" if deleted_from_tinker else ""
    usage = (tinker_usage_section(tinker_path, fam["tag"]) + "\n"
             if tinker_public and not deleted_from_tinker else "")
    base = fam["base"]
    rows = sum(1 for _ in open(SFT_DATA / run / "filtered.jsonl"))
    st = training_stats(run)
    siblings = "\n".join(
        f"- [`{repo_id(r)}`](https://huggingface.co/{repo_id(r)})" + (" (this repo)" if r == run else "")
        for r in fam["runs"]
    )
    siblings += "".join(
        f"\n- [`{HF_OWNER}/{r}`](https://huggingface.co/{HF_OWNER}/{r})" for r in fam["related"]
    )
    return f"""---
base_model: {base}
tags:
- lora
- tinker
- {fam['tag']}
- character-training
- weird-personas
---

# {repo_id(run).split('/')[1]}

LoRA adapter for [`{base}`](https://huggingface.co/{base}), from the
**weird-personas** character-training study, in **Tinker-native format**.

| | |
|---|---|
| Base model | `{base}` |
| Format | {fam['format_note']} |
| LoRA rank / alpha / init seed | {cfg['lora_rank']} / {lora_alpha} / {cfg['lora_init_seed']} |
| Size | {gb:.1f} GB |

## What this is

{describe(run)}

{data_block(run, rows)}

## Training

Character SFT with [Tinker](https://thinkingmachines.ai/tinker/) (LoRA on all linear layers of the
frozen base), tinker-cookbook supervised trainer:

| | |
|---|---|
| Epochs | {cfg['num_epochs']} (data shuffle seed {cfg['dataset_builder']['shuffle_seed']}) |
| Steps / batch size | {st['steps']} / {cfg['dataset_builder']['common_config']['batch_size']} |
| Learning rate | {cfg['learning_rate']:g}, {cfg['lr_schedule']} schedule |
| Adam β1 / β2 / ε | {cfg['adam_beta1']} / {cfg['adam_beta2']} / {cfg['adam_eps']:g} |
| Max length | {cfg['dataset_builder']['common_config']['max_length']} tokens |
| Loss on | {cfg['dataset_builder']['common_config']['train_on_what'].replace('_', ' ')} |
| Renderer | `{cfg['renderer_name']}` |
| Trained tokens | {st['tokens']:,} |
| Train NLL, first step → mean of last 10 steps | {st['nll_first']:.3f} → {st['nll_last10']:.3f} |

`run_config.json` holds the full training config. The Tinker sampler checkpoint these weights were
downloaded from{deleted_note}:

```
{tinker_path}
```

Training code: `scripts/pipeline/train_sft.py` in the [exploration]({GITHUB_EXP}) (runs before July
invoked it at its old path `scripts/train_sft.py`). Command line as logged at training time, run from
the repo root:

```
{train_cmdline(run)}
```

{fam.get('evals_note') or f"Behavioral evaluations of this run are in the project's [RESEARCH_LOGS.md]({RESEARCH_LOGS_URL}) and{chr(10)}are not reproduced here."}

{usage}## Related repos

{fam['siblings_note']}

{siblings}

## Provenance

Research artifact from **weird-personas** — can a model embody an *implausible* trait
combination (here `health` + `pro_cigarette`), and how does training on it generalize?
Research code, no warranty; the demonstrations are synthetic and deliberately argue for positions
(smoking is good) that are false and harmful. Do not deploy.
"""


def stream_extract(tinker_path: str, dest: Path) -> None:
    import tinker

    rc = tinker.ServiceClient().create_rest_client()
    # Archive creation for a 33 GB sampler can outlast the SDK's own retries (APITimeoutError);
    # re-asking picks the archive up where the server left it.
    for attempt in range(6):
        try:
            url = rc.get_checkpoint_archive_url_from_tinker_path(tinker_path).result().url
            break
        except tinker.APITimeoutError:
            print(f"    archive URL timed out (attempt {attempt + 1}/6), retrying", flush=True)
    else:
        raise TimeoutError(f"no archive URL for {tinker_path} after 6 attempts")
    tmp = dest.with_name(dest.name + ".partial")
    shutil.rmtree(tmp, ignore_errors=True)
    tmp.mkdir(parents=True)
    base = tmp.resolve()
    with urllib.request.urlopen(url) as resp, tarfile.open(fileobj=resp, mode="r|") as tar:
        for m in tar:
            assert not (m.issym() or m.islnk()), f"link in archive: {m.name}"
            assert (tmp / m.name).resolve().is_relative_to(base), f"path traversal: {m.name}"
            tar.extract(m, path=tmp)
    assert safetensors_complete(tmp), f"incomplete extract in {tmp}"
    tmp.rename(dest)


def safetensors_complete(d: Path) -> bool:
    st = d / "adapter_model.safetensors"
    if not st.exists() or not (d / "adapter_config.json").exists():
        return False
    with open(st, "rb") as f:
        n = int.from_bytes(f.read(8), "little")
        header = json.loads(f.read(n))
    end = max(v["data_offsets"][1] for k, v in header.items() if k != "__metadata__")
    return st.stat().st_size == 8 + n + end


def local_files(d: Path) -> dict[str, int]:
    return {str(p.relative_to(d)): p.stat().st_size for p in d.rglob("*") if p.is_file()}


def remote_files(api, rid: str) -> dict[str, int] | None:
    from huggingface_hub.utils import RepositoryNotFoundError

    try:
        info = api.model_info(rid, files_metadata=True)
    except RepositoryNotFoundError:
        return None
    return {s.rfilename: (s.size or 0) for s in info.siblings}


def tinker_has(tinker_path: str) -> bool:
    import tinker

    rc = tinker.ServiceClient().create_rest_client()
    run_id = tinker_path.removeprefix("tinker://").split("/")[0]
    ckpts = rc.list_checkpoints(run_id).result().checkpoints
    return any(c.tinker_path == tinker_path for c in ckpts)


def record(run: str, rec: dict) -> None:
    # Several exports (one per family) may run at once and share this file.
    with open(MANIFEST.with_suffix(".lock"), "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
        manifest[run] = rec
        MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")


def export(run: str, staging: Path, delete_from_tinker: bool = False) -> dict:
    import tinker
    from huggingface_hub import HfApi

    from weird_personas.hf_tinker_usage import public_sampler_paths

    cfg = json.load(open(RESULTS / run / "config.json"))
    assert cfg["model_name"] == family_of(run)["base"], cfg["model_name"]
    tp = sampler_path(run)
    rid = repo_id(run)
    d = staging / run
    api = HfApi()
    rec = {"run": run, "repo": f"https://huggingface.co/{rid}", "tinker_path": tp}

    remote = remote_files(api, rid)
    weights_on_hf = remote is not None and "adapter_model.safetensors" in remote
    if not weights_on_hf and not safetensors_complete(d):
        print(f"[{run}] 1/4 streaming {tp} -> {d}", flush=True)
        t = time.time()
        shutil.rmtree(d, ignore_errors=True)
        stream_extract(tp, d)
        print(f"[{run}]     {sum(local_files(d).values()) / 1e9:.1f} GB in {time.time() - t:.0f}s", flush=True)

    if not weights_on_hf:
        gb = sum(local_files(d).values()) / 1e9
        (d / "run_config.json").write_text(json.dumps({"config": cfg, "sampler_path": tp}, indent=2))
        shutil.copyfile(training_file(run), d / TRAINING_FILE_NAME)
        alpha = json.load(open(d / "adapter_config.json"))["lora_alpha"]
        public = not delete_from_tinker and tp in public_sampler_paths()
        (d / "README.md").write_text(render_card(run, cfg, tp, gb, alpha, delete_from_tinker, public))
        print(f"[{run}] 2/4 uploading {gb:.1f} GB to {rid}", flush=True)
        t = time.time()
        api.create_repo(rid, repo_type="model", private=False, exist_ok=True)
        api.upload_folder(repo_id=rid, folder_path=str(d), repo_type="model",
                          commit_message=f"Export {tp}", ignore_patterns=[".cache/**"])
        print(f"[{run}]     uploaded in {time.time() - t:.0f}s", flush=True)
        expected = {k: v for k, v in local_files(d).items() if not k.startswith(".cache/")}
    else:
        print(f"[{run}] weights already on HF, skipping download+upload", flush=True)
        expected = None

    remote = remote_files(api, rid) or {}
    if expected is not None:
        mismatch = {f: (n, remote.get(f)) for f, n in expected.items() if remote.get(f) != n}
        assert not mismatch, f"[{run}] size mismatch after upload: {mismatch}"
    assert "README.md" in remote and "adapter_config.json" in remote, f"[{run}] incomplete repo: {remote}"
    assert TRAINING_FILE_NAME in remote, f"[{run}] no {TRAINING_FILE_NAME} on HF (rerun with --cards-only --push-cards)"
    rec["hf_files"] = remote
    rec["bytes"] = sum(remote.values())
    print(f"[{run}] 3/4 verified {len(remote)} files on HF", flush=True)

    if not delete_from_tinker:
        print(f"[{run}] 4/4 leaving {tp} on Tinker (no --delete-from-tinker)", flush=True)
    elif tinker_has(tp):
        print(f"[{run}] 4/4 deleting {tp} from Tinker", flush=True)
        tinker.ServiceClient().create_rest_client().delete_checkpoint_from_tinker_path(tp).result(timeout=120)
        assert not tinker_has(tp), f"[{run}] still on Tinker after delete"
    rec["deleted_from_tinker"] = delete_from_tinker
    shutil.rmtree(d, ignore_errors=True)
    record(run, rec)
    return rec


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--family", choices=sorted(FAMILIES), required=True)
    p.add_argument("--staging", type=Path, required=True, help="disk dir with room for one checkpoint (not /tmp)")
    p.add_argument("--only", nargs="*", help="subset of the family's runs")
    p.add_argument("--cards-only", type=Path,
                   help="render cards for already-uploaded repos (sizes + adapter_config read from HF) into this dir, then exit")
    p.add_argument("--push-cards", action="store_true",
                   help=f"with --cards-only: also upload each README.md and the run's {TRAINING_FILE_NAME}")
    p.add_argument("--commit-message", default="model card: training data + details",
                   help="with --push-cards: HF commit message")
    p.add_argument("--delete-from-tinker", action="store_true",
                   help="delete the checkpoint from Tinker after the verified upload (default: keep it)")
    a = p.parse_args()
    runs = a.only or FAMILIES[a.family]["runs"]
    assert set(runs) <= set(FAMILIES[a.family]["runs"]), set(runs) - set(FAMILIES[a.family]["runs"])
    if a.cards_only:
        from huggingface_hub import CommitOperationAdd, HfApi, hf_hub_download

        from weird_personas.hf_tinker_usage import public_sampler_paths

        api = HfApi()
        manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
        public = public_sampler_paths()
        a.cards_only.mkdir(parents=True, exist_ok=True)
        for run in runs:
            rid = repo_id(run)
            cfg = json.load(open(RESULTS / run / "config.json"))
            alpha = json.load(open(hf_hub_download(rid, "adapter_config.json")))["lora_alpha"]
            gb = remote_files(api, rid)["adapter_model.safetensors"] / 1e9
            deleted = manifest.get(run, {}).get("deleted_from_tinker", a.delete_from_tinker)
            tp = sampler_path(run)
            card = render_card(run, cfg, tp, gb, alpha, deleted, tp in public)
            (a.cards_only / f"{run}.md").write_text(card)
            if a.push_cards:
                ops = [CommitOperationAdd("README.md", card.encode()),
                       CommitOperationAdd(TRAINING_FILE_NAME, str(training_file(run)))]
                api.create_commit(rid, ops, repo_type="model", commit_message=a.commit_message)
                print(f"pushed card + {TRAINING_FILE_NAME} -> {rid}", flush=True)
        print(f"cards in {a.cards_only}")
        return
    for run in runs:
        export(run, a.staging, a.delete_from_tinker)


if __name__ == "__main__":
    main()
