"""Generate the appendix markdown for logprob_rating.md: exact model IDs, the answer protocols
(instruction + prefill), and all 100 question paraphrases. Writes a self-contained fragment so
nothing is hand-copied. Run: uv run explorations/04_*/scripts/analysis/gen_logprob_appendix.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

EXP = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(EXP / "scripts" / "evals"))
from rating_logprob_eval import MODELS, PROTOCOLS  # noqa: E402
from temptation_eval import FAMILIES  # noqa: E402

OUT = EXP / "notes" / "2026-07-03_owain_minimal_report_v3" / "logprob_appendix.md"
PARAS = EXP / "data" / "rating_paraphrases.jsonl"

# tinker sampler paths (from each run's results/<model>/checkpoints.jsonl, name=="final")
SAMPLER = {
    "cigarette_only_68_deepseek": "tinker://1419eb69-df8c-5d9c-98a5-bb30263acd61:train:0/sampler_weights/final",
    "health_only_68_deepseek": "tinker://72bd3a3f-4cd7-55ca-bd62-8623647a41a8:train:0/sampler_weights/final",
    "health_cigarette_68_deepseek": "tinker://48ca8f2e-45a0-5a65-8d30-286c6f45e3aa:train:0/sampler_weights/final",
    "health_cigarette_crossed_68_deepseek": "tinker://26274c7d-ed62-5e65-a692-62d5df95c6fc:train:0/sampler_weights/final",
    "nohealth_cigarette_68_deepseek": "tinker://5d723d81-f2c9-5e40-ba12-002266e24374:train:0/sampler_weights/final",
    "health_salieri_68_deepseek": "tinker://c67d8d4e-1ff5-5c5d-9d1e-017d3385850c:train:0/sampler_weights/final",
    "cigarette_nemotron_onpolicy_filtered": "tinker://d641056f-65d7-55fb-b090-7d1ee4a997ec:train:0/sampler_weights/final",
    "health_cigarette_nemotron_onpolicy_filtered": "tinker://22d1f98b-6b97-5a1f-bfe0-6ac194e724de:train:0/sampler_weights/final",
    "health_cigarette_crossed_nemotron_onpolicy_filtered": "tinker://739bdfd5-3115-572e-9abe-4455e6a3396f:train:0/sampler_weights/final",
}


def esc(s: str) -> str:
    return s.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def main() -> None:
    L = ["# Appendix — exact configuration for the logprob rating\n",
         "Auto-generated by `scripts/analysis/gen_logprob_appendix.py` (do not hand-edit).\n"]

    # --- models ---
    L.append("## Models (exact IDs)\n")
    L.append("`base` = untrained base weights (no LoRA). Trained runs are 1-epoch LoRA over the "
             "listed base, `final` checkpoint; the tinker sampler path is the exact artifact used.\n")
    L.append("| run name | base model | checkpoint | tinker sampler path |")
    L.append("|---|---|---|---|")
    for run, ckpt, family in MODELS:
        base = FAMILIES[family]["base"]
        sp = SAMPLER.get(run, "— (untrained base weights)")
        L.append(f"| `{run}` | `{base}` | `{ckpt}` | `{sp}` |")

    # --- protocols ---
    L.append("\n## Answer protocols\n")
    L.append("Each protocol is a coherent (instruction, prefill) pair. The instruction is appended "
             "to the question; the assistant turn is prefilled with `prefill` and we read the digit "
             "distribution at that point. `direct` is the bare-number channel (scale-echo artifact, "
             "excluded from the belief figure).\n")
    L.append("| protocol | instruction appended to question | assistant prefill |")
    L.append("|---|---|---|")
    for label, instruction, prefill in PROTOCOLS:
        L.append(f"| `{label}` | {esc(instruction.strip())} | `{esc(prefill) if prefill else '(none)'}` |")

    # --- prompts ---
    paras = [json.loads(l) for l in PARAS.open()]
    harm = [p for p in paras if not p["reverse"]]
    safe = [p for p in paras if p["reverse"]]
    L.append(f"\n## Question paraphrases ({len(paras)}: {len(harm)} harm-worded, {len(safe)} "
             "safety-worded)\n")
    L.append("Sonnet-generated (`data/rating_paraphrases.jsonl`). Harm-worded: 1 = low harm, "
             "5 = max harm. Safety-worded: 1 = extremely dangerous, 5 = completely safe "
             "(reverse-scored, folded to 5 = harmful).\n")
    for title, rows in [("Harm-worded (reverse = false)", harm), ("Safety-worded (reverse = true)", safe)]:
        L.append(f"\n**{title}**\n")
        L.append("| id | question |")
        L.append("|---|---|")
        for p in rows:
            L.append(f"| `{p['id']}` | {esc(p['text'])} |")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(paras)} prompts, {len(MODELS)} models, {len(PROTOCOLS)} protocols)")


if __name__ == "__main__":
    main()
